# yaml-language-server: $schema=https://www.schemastore.org/github-action.json
name: "Prebuild DevContainer"
description: "Build and push devcontainer image to GitHub Container Registry"
inputs:
  github_token:
    description: "GitHub token for registry authentication"
    required: true
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7
      with:
        persist-credentials: false

    - name: Convert repository owner/repo to lowercase
      id: repo_name
      shell: bash
      run: echo "lowercase=${GITHUB_REPOSITORY,,}" >> "$GITHUB_OUTPUT"

    - name: Login to GitHub Container Registry
      uses: docker/login-action@650006c6eb7dba73a995cc03b0b2d7f5ca915bee # v4.2.0
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ inputs.github_token }}

    - name: Pre-build dev container image
      uses: devcontainers/ci@513af61f4de4f75d37e4438f184ba4358f0fc1ca # v0.3.1900000450
      with:
        imageName: ghcr.io/${{ steps.repo_name.outputs.lowercase }}/devcontainer
        cacheFrom: ghcr.io/${{ steps.repo_name.outputs.lowercase }}/devcontainer
        refFilterForPush: refs/heads/main
        noCache: false
