# yaml-language-server: $schema=https://www.schemastore.org/github-action.json
name: "Setup Rust"
description: "Setup rust"
inputs:
  sccache:
    description: "sccache version"
    required: false
    default: ""
  sccache_disable_annotations:
    description: "sccache disable_annotations"
    required: false
    default: "false"

runs:
  using: "composite"
  steps:
    - name: Run sccache-cache
      uses: mozilla-actions/sccache-action@9e7fa8a12102821edf02ca5dbea1acd0f89a2696 # v0.0.10
      with:
        disable_annotations: ${{ inputs.sccache_disable_annotations == 'true' }}
        version: ${{ inputs.sccache }}

    - name: Set RUSTC_WRAPPER
      shell: bash
      run: echo "RUSTC_WRAPPER=sccache" >> "$GITHUB_ENV"

    - name: Cache rustup
      uses: actions/cache@caa296126883cff596d87d8935842f9db880ef25 # v5.1.0
      with:
        path: |
          ~/.rustup/settings.toml
          ~/.rustup/toolchains/1.*
        key: v0-rust-rustup-${{ runner.os }}-${{ runner.arch }}-${{ hashFiles('**/rust-toolchain.toml') }}

    - uses: actions-rust-lang/setup-rust-toolchain@166cdcfd11aee3cb47222f9ddb555ce30ddb9659 # v1.17.0
      with:
        cache-shared-key: cargo-${{ runner.os }}-${{ runner.arch }}-${{ hashFiles('**/Cargo.lock') }}
